# Generated by Django 3.0.2 on 2020-01-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
